name: useful_packages
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.8.0-171.0.dev







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  device_preview: ^1.2.0
  video_player: ^2.7.0
  feedback: ^3.1.0
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  animated_list_plus: ^0.5.2
  animate_do: ^4.2.0
  simple_animations: ^5.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.2
  flutter_animation_plus: ^0.0.7
  chart_it: ^0.2.2
  syncfusion_flutter_charts: ^29.1.40
  fl_chart: ^0.71.0
  rive: ^0.13.20
  device_info_plus: ^11.4.0
  url_launcher: ^6.3.1
  go_router: ^15.1.1
  flutter_launcher_icons: ^0.14.3
  connectivity_plus: ^6.1.4
  flutter_secure_storage: ^9.2.4
  lottie: ^3.3.1
  awesome_snackbar_content: ^0.1.6
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  flutter_iconly: ^1.0.1
  animated_icon_button: ^1.0.2
  flutter_vector_icons: ^2.0.0
  line_icons: ^2.0.3
  confetti: ^0.8.0
  animated_theme_switcher: ^2.0.10
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true

  assets:
    - assets/rive/boy.riv
    - assets/icons/icon.png
    - assets/lottie/pencil_draw.json

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
